### ISSUE TITLE
validator

### ISSUE THREAD

**Issue by siddo420** [primus/mirage#3]
I'm a little confused about the purpose of this validator method. Why it doesn't always get called when client tries to connect to server?

In my tests, clients can easily make connections with server although I have a validator method that should at least get called (and block that unknown connection).

**Comment by lpinca** [comment]
How is your validator defined? It should definitely run every time a [client attempts a connection](https://github.com/primus/mirage/blob/98aac160578fa0257de2a221f6f44096ce9168db/index.js#L237-L240) (if the client sends the mirage id during the connection).

**Comment by siddo420** [comment]
Client wasn't sending a mirage ID in my case, but anybody from the client side can do that. And, connection would be allowed easily.

I guess, I need to check for the presence of a mirage ID in authorization layer and how do I do that?

Is there any way I could detect mirage IDs in primus.authorize layer? This one comes before mirage in my case.

**Comment by lpinca** [comment]
You can check the `_mirage` property of the parsed query string:
```js
primus.authorize((req, next) => {
  if (req.query._mirage) return next();

  next(new Error('message'));
});
```
Keep in mind that by doing this `mirage` will not generate an id for you if you don't provide one.

**Comment by siddo420** [comment]
seems to work .. will reopen if needed
