### ISSUE TITLE
compatibility with primus 6.0.2?

### ISSUE THREAD

**Issue by siddo420** [primus/mirage#6]
Is it compatible with primus 6.0.2?

After upgrading both primus and mirage to latest, I am now getting "PrimusError: Middleware should be a function that accepts at least 2 args"  at the line where I am using mirage
```
 primus.use( 'mirage',       require( 'mirage' ));
```

**Comment by lpinca** [comment]
You have to use the `plugin` method. The breaking changes in version 6 are listed [here](https://github.com/primus/primus/releases/tag/6.0.0).
